### ISSUE TITLE
About extracting external metrics..

### ISSUE THREAD

**Issue by shengminp** [addb-swstarlab/RocksDB-data-generation#3]
Thanks for answering my previous question.

I have one more question about that!
I wonder the exact metric's name of the metrics, which are waf, saf, rate and time, on statistics results text file.

**Comment by huijunjin** [comment]
WAF: write amplification factor
SAF: space amplification factor
RATE: rate
TIME: time

We do not use SAF as the external metrics for it highly depends on the compression ratio (mentioned in the document)
